import { useMutation, useQuery } from '@tanstack/react-query'
import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, Bot, Check, Circle, Database, FileCode2, Layers3, ShieldCheck, XCircle } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { analysisService } from '@/services/analysisService'
import { SeverityBadge } from '@/components/SeverityBadge'
import { ReviewTerminal } from './ReviewTerminal'

const stageNames = ['Secure upload', 'Archive preparation', 'Repository inventory', 'Confidential-data masking', 'Review grouping', 'Claude analysis', 'Finding validation', 'Report generation']
const finishedStatuses = new Set(['COMPLETED', 'PARTIALLY_COMPLETED', 'CANCELLED', 'FAILED', 'EXPIRED'])
const stageByStatus: Record<string, number> = { PREPARING: 0, UPLOADED: 0, VALIDATING_ARCHIVE: 1, EXTRACTING: 1, BUILDING_INVENTORY: 2, SCANNING_CONFIDENTIAL_DATA: 3, MASKING_CONTENT: 3, CREATING_REVIEW_UNITS: 4, AI_REVIEW_IN_PROGRESS: 5, VALIDATING_FINDINGS: 6, CALCULATING_SCORES: 7, GENERATING_REPORT: 7, FINAL_CONFIDENTIALITY_CHECK: 7 }
const failureStageByCode: Record<string, number> = { PREPARE_PROJECT_FAILED: 1, CREATE_REVIEW_UNITS_FAILED: 4, PROCESS_REVIEW_UNITS_FAILED: 5, VALIDATE_FINDINGS_FAILED: 6, FINALIZE_REPORT_FAILED: 7 }

export function AnalysisPage() {
  const { jobId = '' } = useParams()
  const navigate = useNavigate()
  const { data: job, isLoading, error } = useQuery({ queryKey: ['analysis', jobId], queryFn: () => analysisService.get(jobId), refetchInterval: (query) => finishedStatuses.has(query.state.data?.status ?? '') ? false : 5000 })
  const { data: findings = [] } = useQuery({ queryKey: ['findings', jobId], queryFn: () => analysisService.findings(jobId), refetchInterval: finishedStatuses.has(job?.status ?? '') ? false : 5000 })
  const { data: usage } = useQuery({ queryKey: ['anthropic-usage', jobId], queryFn: () => analysisService.anthropicUsage(jobId), refetchInterval: finishedStatuses.has(job?.status ?? '') ? false : 5000 })
  const cancel = useMutation({ mutationFn: () => analysisService.cancel(jobId), onSuccess: () => navigate('/') })
  if (isLoading) return <div className="surface h-96 animate-pulse" />
  if (error || !job) return <div className="surface p-8"><XCircle className="text-rose-500" /><h2 className="mt-3 font-semibold">Analysis unavailable</h2><p className="mt-1 text-sm text-slate-500">{error instanceof Error ? error.message : 'The requested analysis could not be loaded.'}</p></div>
  const hasReport = job.status === 'COMPLETED' || job.status === 'PARTIALLY_COMPLETED'
  const failed = job.status === 'FAILED'
  const currentIndex = hasReport ? stageNames.length : failed ? (failureStageByCode[job.errorCode ?? ''] ?? 0) : (stageByStatus[job.status] ?? 0)
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><span className="rounded-full bg-accent-50 px-2.5 py-1 text-[10px] font-bold text-accent-700 dark:bg-accent-500/10 dark:text-accent-300">{job.status.replaceAll('_', ' ')}</span><span className="text-xs text-slate-500">Analysis {job.id.slice(0, 8)}</span></div><h2 className="mt-3 text-3xl font-bold tracking-tight">{job.projectName}</h2><p className="mt-1 text-sm text-slate-500">{hasReport ? 'Validation and report generation are complete.' : finishedStatuses.has(job.status) ? 'Processing has stopped.' : 'You can close this page. Processing continues securely.'}</p></div>{hasReport ? <Link className="btn-primary" to={`/analysis/${job.id}/report`}>View final report</Link> : !finishedStatuses.has(job.status) && <button className="btn-secondary text-rose-600" onClick={() => cancel.mutate()} disabled={cancel.isPending}>Cancel analysis</button>}</div>
    <ReviewTerminal job={job} />
    <section className="surface overflow-hidden"><div className="border-b p-6"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold">{job.currentStage}</p><p className="mt-1 text-xs text-slate-500">{job.progressPercentage}% complete</p></div><span className={`font-mono text-2xl font-bold ${failed ? 'text-rose-600' : 'text-accent-600'}`}>{job.progressPercentage}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full transition-all duration-700 ${failed ? 'bg-rose-500' : 'bg-accent-500'}`} style={{ width: `${job.progressPercentage}%` }} /></div></div>
      <div className="grid gap-px bg-slate-200 dark:bg-slate-800 sm:grid-cols-2 xl:grid-cols-4">{stageNames.map((stage, index) => { const done = index < currentIndex || hasReport; const active = index === currentIndex; return <div key={stage} className="flex items-center gap-3 bg-white p-4 dark:bg-slate-900"><span className={`grid size-7 place-items-center rounded-full ${done ? 'bg-accent-600 text-white' : active && failed ? 'border-2 border-rose-500 text-rose-600' : active ? 'border-2 border-accent-500 text-accent-600' : 'bg-slate-100 text-slate-400 dark:bg-slate-800'}`}>{active && failed ? <XCircle size={14} /> : done ? <Check size={14} /> : <Circle size={10} fill="currentColor" />}</span><span className={`text-xs font-medium ${active && failed ? 'text-rose-600' : active ? 'text-accent-600' : ''}`}>{stage}</span></div> })}</div>
    </section>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MiniStat icon={FileCode2} label="Files discovered" value={job.totalFiles} /><MiniStat icon={ShieldCheck} label="Files included" value={job.includedFiles} /><MiniStat icon={Layers3} label="Review units" value={`${job.completedReviewUnits}/${job.totalReviewUnits}`} /><MiniStat icon={AlertTriangle} label="Preliminary findings" value={findings.length} /></div>
    <section><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><h3 className="font-semibold">Claude API usage</h3><p className="mt-1 text-xs text-slate-500">Exact provider-reported usage for this analysis job. Cached tokens are shown separately.</p></div>{usage?.rejectedCalls ? <span className="text-xs font-medium text-amber-600">{usage.rejectedCalls} rejected call{usage.rejectedCalls === 1 ? '' : 's'}</span> : null}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MiniStat icon={Bot} label={`${usage?.successfulCalls ?? 0} successful API calls`} value={usage?.apiCalls ?? 0} /><MiniStat icon={ArrowDownToLine} label="Uncached input tokens" value={formatCount(usage?.inputTokens ?? 0)} /><MiniStat icon={ArrowUpFromLine} label="Output tokens" value={formatCount(usage?.outputTokens ?? 0)} /><MiniStat icon={Database} label="Cache write + read tokens" value={formatCount((usage?.cacheCreationInputTokens ?? 0) + (usage?.cacheReadInputTokens ?? 0))} /></div></section>
    <section className="surface p-6"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-start"><div><h3 className="font-semibold">Preliminary findings — final validation pending</h3><p className="mt-1 text-xs text-slate-500">Structured observations appear as review units finish. They are not confirmed vulnerabilities until validated.</p></div><span className="text-xs text-slate-500">Polling every 5 seconds</span></div>{findings.length ? <div className="mt-5 divide-y">{findings.map((finding) => <article key={finding.id} className="py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-center gap-2"><SeverityBadge severity={finding.severity} /><span className="text-[10px] font-bold text-slate-500">{finding.category.replaceAll('_', ' ')}</span><span className="text-[10px] text-slate-500">{finding.confidence} confidence</span></div><h4 className="mt-2 text-sm font-semibold">{finding.title}</h4><p className="mt-1 font-mono text-[11px] text-slate-500">{finding.maskedFilePath}{finding.lineStart ? `:${finding.lineStart}` : ''}</p></article>)}</div> : <div className="mt-5 rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Findings will appear after secure preparation and review grouping.</div>}</section>
  </div>
}

function MiniStat({ icon: Icon, label, value }: { icon: typeof FileCode2; label: string; value: string | number }) { return <div className="surface flex items-center gap-4 p-4"><span className="rounded-xl bg-slate-100 p-2.5 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><Icon size={18} /></span><div><p className="text-xl font-bold">{value}</p><p className="text-xs text-slate-500">{label}</p></div></div> }

function formatCount(value: number): string { return new Intl.NumberFormat('en', { notation: value >= 10000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value) }
