import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Activity, ArrowRight, Bot, CircleGauge, Clock3, FileCode2, FolderKanban, Search, ShieldAlert, Sparkles, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { adminAnalyticsService, type AdminUserAnalytics } from '@/services/adminAnalyticsService'

const severityColors = ['#e11d48', '#f97316', '#f59e0b', '#0ea5e9', '#64748b']
const number = new Intl.NumberFormat('en', { notation: 'compact', maximumFractionDigits: 1 })

function format(value: number) { return number.format(value) }
function scoreTone(score: number | null) { return score == null ? 'text-slate-400' : score >= 85 ? 'text-emerald-600' : score >= 70 ? 'text-amber-600' : 'text-rose-600' }
function date(value: string | null) { return value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) : 'No activity' }

function Metric({ label, value, detail, icon: Icon, tone = 'accent' }: { label: string; value: string | number; detail: string; icon: typeof Users; tone?: 'accent' | 'rose' | 'amber' | 'blue' }) {
  const colors = { accent: 'bg-accent-50 text-accent-700 dark:bg-accent-500/10 dark:text-accent-300', rose: 'bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300', amber: 'bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-300', blue: 'bg-sky-50 text-sky-700 dark:bg-sky-500/10 dark:text-sky-300' }
  return <div className="surface p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.13em] text-slate-400">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight">{value}</p></div><span className={`rounded-xl p-2.5 ${colors[tone]}`}><Icon size={19} /></span></div><p className="mt-2 text-xs text-slate-500">{detail}</p></div>
}

function Status({ value }: { value: string }) {
  const completed = value === 'COMPLETED' || value === 'PARTIALLY_COMPLETED'
  const failed = value === 'FAILED' || value === 'CANCELLED' || value === 'EXPIRED'
  return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${completed ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300' : failed ? 'bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300' : 'bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-300'}`}>{value.replaceAll('_', ' ')}</span>
}

export function AdminDashboardPage() {
  const [search, setSearch] = useState('')
  const { data, isLoading, error, dataUpdatedAt } = useQuery({ queryKey: ['admin-analytics'], queryFn: adminAnalyticsService.get, refetchInterval: 60_000 })
  const users = useMemo(() => data?.users.filter((user) => `${user.displayName} ${user.email}`.toLowerCase().includes(search.toLowerCase())) ?? [], [data?.users, search])
  if (isLoading) return <div className="space-y-5"><div className="h-28 animate-pulse rounded-2xl bg-slate-200/70 dark:bg-slate-800" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div className="h-36 animate-pulse rounded-2xl bg-slate-200/70 dark:bg-slate-800" key={index} />)}</div></div>
  if (error || !data) return <div className="surface p-8"><ShieldAlert className="text-rose-500" /><h2 className="mt-4 text-xl font-bold">Admin analytics unavailable</h2><p className="mt-2 text-sm text-slate-500">The secure analytics service could not be loaded. Refresh the page or verify the Edge Function deployment.</p></div>

  const totalTokens = data.tokens.inputTokens + data.tokens.outputTokens + data.tokens.cacheCreationTokens + data.tokens.cacheReadTokens
  const completionRate = data.totals.analyses ? Math.round((data.totals.completedAnalyses / data.totals.analyses) * 100) : 0
  const successRate = data.tokens.apiCalls ? Math.round((data.tokens.successfulCalls / data.tokens.apiCalls) * 100) : 0
  const severity = Object.entries(data.severity).map(([name, value]) => ({ name, value }))
  const topTokenUsers = [...data.users].sort((a, b) => b.totalTokens - a.totalTokens).slice(0, 7)
  const trend = data.trend.map((item) => ({ ...item, label: new Date(`${item.date}T00:00:00Z`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }))

  return <div className="space-y-7">
    <section className="relative overflow-hidden rounded-3xl border border-accent-100 bg-gradient-to-br from-white via-accent-50/70 to-sky-50 px-6 py-7 text-slate-950 shadow-card dark:border-slate-800 dark:from-slate-950 dark:via-slate-950 dark:to-[#06252a] dark:text-white sm:px-8">
      <div className="pointer-events-none absolute -right-20 -top-24 size-72 rounded-full bg-accent-400/20 blur-3xl dark:bg-accent-500/15" />
      <div className="pointer-events-none absolute -bottom-24 left-1/3 size-56 rounded-full bg-sky-300/15 blur-3xl dark:bg-sky-500/5" />
      <div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-accent-700 dark:text-accent-300"><Sparkles size={14} /> Administrator intelligence</div><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Platform analytics</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-400">Cross-user adoption, repository risk, code quality, processing health, and Anthropic consumption in one protected view.</p></div><div className="rounded-2xl border border-white/80 bg-white/70 px-4 py-3 text-xs text-slate-500 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/5 dark:text-slate-400"><p className="font-semibold text-slate-800 dark:text-slate-200">Live operational view</p><p className="mt-1">Updated {new Date(dataUpdatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · refreshes every minute</p></div></div>
    </section>

    {data.totals.pendingUsers > 0 && <Link to="/admin/users" className="flex items-center justify-between rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-amber-900 transition hover:border-amber-300 dark:border-amber-500/20 dark:bg-amber-500/10 dark:text-amber-200"><span className="flex items-center gap-3"><Clock3 size={19} /><span><strong>{data.totals.pendingUsers} access request{data.totals.pendingUsers === 1 ? '' : 's'} pending</strong><span className="ml-2 text-sm opacity-70">Review users waiting for approval.</span></span></span><ArrowRight size={18} /></Link>}

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">
      <Metric label="Users" value={data.totals.registeredUsers} detail={`${data.totals.approvedUsers} approved`} icon={Users} />
      <Metric label="Projects" value={data.totals.projects} detail={`${data.totals.analyses} analyses submitted`} icon={FolderKanban} tone="blue" />
      <Metric label="Files reviewed" value={format(data.totals.filesAnalyzed)} detail="Supported source files" icon={FileCode2} />
      <Metric label="Findings" value={format(data.totals.findings)} detail={`${data.severity.CRITICAL} critical · ${data.severity.MAJOR} major`} icon={ShieldAlert} tone="rose" />
      <Metric label="Code quality" value={data.totals.averageScore == null ? '—' : `${data.totals.averageScore}`} detail="Average score out of 100" icon={CircleGauge} tone="amber" />
      <Metric label="AI tokens" value={format(totalTokens)} detail={`${format(data.tokens.apiCalls)} provider calls`} icon={Bot} tone="blue" />
    </section>

    <section className="grid gap-6 xl:grid-cols-[1.6fr_.8fr]">
      <div className="surface p-5 sm:p-6"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><h3 className="font-semibold">30-day activity</h3><p className="mt-1 text-xs text-slate-500">Analysis submissions and validated issue volume</p></div><span className="text-xs font-semibold text-emerald-600">{completionRate}% completion rate</span></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ left: -18, right: 4 }}><defs><linearGradient id="analysisFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0d9488" stopOpacity={0.3} /><stop offset="100%" stopColor="#0d9488" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#94a3b833" /><XAxis dataKey="label" tick={{ fontSize: 10 }} interval={5} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip /><Area type="monotone" dataKey="findings" stroke="#f97316" fill="none" strokeWidth={2} /><Area type="monotone" dataKey="analyses" stroke="#0d9488" fill="url(#analysisFill)" strokeWidth={2.5} /></AreaChart></ResponsiveContainer></div><div className="mt-2 flex gap-5 text-xs text-slate-500"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-accent-600" />Analyses</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-orange-500" />Findings</span></div></div>
      <div className="surface p-5 sm:p-6"><h3 className="font-semibold">Risk composition</h3><p className="mt-1 text-xs text-slate-500">Findings across all submitted repositories</p><div className="h-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={severity} dataKey="value" nameKey="name" innerRadius={56} outerRadius={82} paddingAngle={3}>{severity.map((item, index) => <Cell key={item.name} fill={severityColors[index]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="space-y-2">{severity.map((item, index) => <div key={item.name} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-500"><i className="size-2 rounded-full" style={{ backgroundColor: severityColors[index] }} />{item.name}</span><strong>{format(item.value)}</strong></div>)}</div></div>
    </section>

    <section className="surface overflow-hidden"><div className="border-b p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h3 className="font-semibold">User performance</h3><p className="mt-1 text-xs text-slate-500">Project adoption, repository health, findings, and attributed token consumption</p></div><label className="relative block lg:w-72"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input className="field !pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search user or email" /></label></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500 dark:bg-slate-950/50"><tr><th className="px-5 py-3">User</th><th className="px-4 py-3">Projects</th><th className="px-4 py-3">Analyses</th><th className="px-4 py-3">Files</th><th className="px-4 py-3">Findings</th><th className="px-4 py-3">Quality</th><th className="px-4 py-3">Dev quality</th><th className="px-4 py-3">Tokens</th><th className="px-4 py-3">Last activity</th></tr></thead><tbody className="divide-y">{users.map((user) => <UserRow key={user.id} user={user} />)}</tbody></table>{users.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No users match this search.</p>}</div></section>

    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <div className="surface p-5 sm:p-6"><div className="flex items-end justify-between"><div><h3 className="font-semibold">Token consumption by user</h3><p className="mt-1 text-xs text-slate-500">Input, output, and cache tokens attributed by analysis owner</p></div><span className="text-xs font-semibold text-slate-500">{successRate}% call success</span></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={topTokenUsers} layout="vertical" margin={{ left: 12, right: 8 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#94a3b833" /><XAxis type="number" tickFormatter={format} tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="displayName" width={90} tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value: number) => format(value)} /><Bar dataKey="inputTokens" stackId="tokens" fill="#0d9488" /><Bar dataKey="outputTokens" stackId="tokens" fill="#38bdf8" /><Bar dataKey="cacheTokens" stackId="tokens" fill="#a78bfa" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div><div className="flex flex-wrap gap-4 text-xs text-slate-500"><span>Input <b className="text-accent-600">{format(data.tokens.inputTokens)}</b></span><span>Output <b className="text-sky-500">{format(data.tokens.outputTokens)}</b></span><span>Cache <b className="text-violet-500">{format(data.tokens.cacheCreationTokens + data.tokens.cacheReadTokens)}</b></span><span>Rejected calls <b className="text-rose-500">{data.tokens.rejectedCalls}</b></span></div></div>
      <div className="surface overflow-hidden"><div className="border-b p-5 sm:p-6"><h3 className="font-semibold">Recent analyses</h3><p className="mt-1 text-xs text-slate-500">Latest activity across all users</p></div><div className="divide-y">{data.recentAnalyses.slice(0, 7).map((job) => <div key={job.id} className="flex items-center gap-3 px-5 py-3.5"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-slate-100 dark:bg-slate-800"><Activity size={15} /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{job.projectName}</p><p className="mt-1 truncate text-[10px] text-slate-500">{job.userName} · {date(job.updatedAt)} · {job.findings} findings</p></div><Status value={job.status} /></div>)}</div></div>
    </section>

    <section className="surface overflow-hidden"><div className="border-b p-5 sm:p-6"><h3 className="font-semibold">Highest-risk repositories</h3><p className="mt-1 text-xs text-slate-500">Prioritized by critical issues, then total findings</p></div><div className="grid divide-y lg:grid-cols-2 lg:divide-x lg:divide-y-0">{data.projects.slice(0, 6).map((project, index) => <div className="flex items-center gap-4 p-5" key={project.id}><span className={`grid size-9 shrink-0 place-items-center rounded-xl text-sm font-bold ${index < 3 ? 'bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300' : 'bg-slate-100 dark:bg-slate-800'}`}>{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{project.name}</p><p className="mt-1 truncate text-xs text-slate-500">{project.ownerName} · {project.analyses} analyses</p></div><div className="text-right"><p className="text-sm font-bold text-rose-600">{project.criticalFindings} critical</p><p className="mt-1 text-[10px] text-slate-500">{project.findings} total · score {project.latestScore ?? '—'}</p></div></div>)}</div></section>
  </div>
}

function UserRow({ user }: { user: AdminUserAnalytics }) {
  return <tr className="transition hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-accent-50 font-bold text-accent-700 dark:bg-accent-500/10 dark:text-accent-300">{user.displayName.slice(0, 2).toUpperCase()}</span><div className="min-w-0"><div className="flex items-center gap-2"><p className="max-w-44 truncate font-semibold">{user.displayName}</p>{user.role === 'ADMIN' && <span className="rounded bg-slate-900 px-1.5 py-0.5 text-[8px] font-bold text-white dark:bg-white dark:text-slate-900">ADMIN</span>}</div><p className="max-w-52 truncate text-[10px] text-slate-500">{user.email}</p></div></div></td><td className="px-4 py-4 font-semibold">{user.projects}</td><td className="px-4 py-4"><strong>{user.analyses}</strong><p className="mt-1 text-[10px] text-slate-400">{user.completedAnalyses} complete · {user.failedAnalyses} failed</p></td><td className="px-4 py-4">{format(user.filesAnalyzed)}</td><td className="px-4 py-4"><strong>{format(user.findings)}</strong><p className="mt-1 text-[10px] text-rose-500">{user.criticalFindings} critical · {user.majorFindings} major</p></td><td className={`px-4 py-4 text-base font-bold ${scoreTone(user.averageScore)}`}>{user.averageScore ?? '—'}</td><td className={`px-4 py-4 font-bold ${scoreTone(user.developerQualityScore)}`}>{user.developerQualityScore ?? '—'}</td><td className="px-4 py-4"><strong>{format(user.totalTokens)}</strong><p className="mt-1 text-[10px] text-slate-400">{format(user.apiCalls)} calls</p></td><td className="px-4 py-4 text-slate-500">{date(user.lastActivityAt)}</td></tr>
}
